# Generated by Django 5.0.7 on 2024-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_type", models.CharField(max_length=100)),
                ("trans_id", models.CharField(max_length=100, unique=True)),
                ("trans_time", models.DateTimeField()),
                ("trans_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("business_short_code", models.CharField(max_length=20)),
                (
                    "bill_ref_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "third_party_trans_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("msisdn", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("month_paid", models.CharField(default="Unknown", max_length=20)),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
